name: CI

on:
  create:
    tags:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O ./src/yolov3-tiny.weights https://pjreddie.com/media/files/yolov3-tiny.weights
      - name: Run build
        run: make all
      - name: inference test
        run: ./test.sh amd64
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: output
